cart/urls.py
from django.urls import path
from cart import views, api

app_name = 'cart'

urlpatterns = [
    path('cart-page/', views.CartView.as_view(), name="cart-page"),
    path('cart-detail/<int:id>/', views.DetailView.as_view(), name="cart-detail-page"),

    path('cartAPI/', api.CartViewSet.as_view({
        'get': 'get',
        'post': 'post',
    }), name="cart_api"),

    path('cart-detail-api/<int:id>/', api.CartViewSet.as_view({
        'post': 'delete',
        'get': 'get_detail',
        'put': 'put'
    }), name="cart-delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('market.urls')),
    path('cart/', include('cart.urls')),
    path('transaction/', include('transaction.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('auth/', include('rest_authtoken.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
from django.urls import path
from market import views, api

app_name = 'market'

urlpatterns = [

    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),
    path('product-view/<int:id>/', views.DetailView.as_view(), name="productDetail"),
    path('wishlist-page/', views.WishlistView.as_view(), name="wishlist-page"),

    path('list/', api.ProductViewSet.as_view({
        'get': 'get_all',
    }), name="product_list"),

    path('product/', api.ProductViewSet.as_view({
        'get': 'get_owned',
        'post': 'post',
    }), name="product"),

    path('product-detail/<int:id>/', api.ProductViewSet.as_view({
        'get': 'get',
        'put': 'put',
        'post': 'delete',
        'patch': 'patch',
    }), name="product-detail"),

    path('product-wishlist/<int:id>/', api.ProductViewSet.as_view({
        'post': 'wishlist_product'
    }), name="product-wishlist")
]

transaction/urls.py
from django.urls import path
from transaction import views, api

app_name = 'transaction'

urlpatterns = [
    path('buyer/', views.BuyerView.as_view(), name='buyer'),
    path('seller/', views.SellerView.as_view(), name='seller'),
    
    path('transact/', api.TransactionViewSet.as_view({
        'get': 'get',
        'post': 'post',
    }), name="transact")
]

users/urls.py
from django.urls import path
from users import views, api

app_name = 'users'

urlpatterns = [
    path("profile-page/<int:id>/", views.ProfileView.as_view(), name="profile-page"),
    path("register-page/", views.RegisterView.as_view(), name="register-page"),
    path("login-page/", views.LoginView.as_view(), name="login-page"),
    path("update-profile-page/", views.UpdateView.as_view(), name="update-profile-page"),
    path("logout/", views.LogoutView, name="logout"),

    path("register/", api.RegisterViewSet.as_view({
        'post': 'post',
    }), name='register'),

    path("login/", api.LoginViewSet.as_view({
        'post': 'post',
    }), name="login"),

    path("profile/<int:id>/", api.UserViewSet.as_view({
        'get':'get',
        'put': 'put',
    }), name="profile"),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Marketplace</title>
  <base href="/">

  {# NOTE: Change this to CDN #}

  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootswatch@5.2.3/dist/lux/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">

  {% block extra_css %}
  {% endblock %}

  <!-- Custom styles for this template -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>
<body>
    {% block navigation %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'market:dashboard' %}">Marketplace</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Transaction</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'transaction:buyer' %}">Bought</a>
                <a class="dropdown-item" href="{% url 'transaction:seller' %}">Sold</a>
              </div>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:profile-page' user.id %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cart:cart-page' %}">Cart</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'market:wishlist-page' %}">Wishlist</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login-page' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register-page' %}">Register</a>
            </li>
            {% endif %}
          </ul>
          <div class="d-flex">
            {% if user.is_authenticated %}
            <h5 style="color: white;">{{user}}</h5>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    {% endblock %}

    {% block content %}
      
    {% endblock %}
    {% block footer %}{% endblock %}

    <!-- Bootstrap core JavaScript ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="{% static 'js/jquery-3.6.3.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/c1cb195988.js" crossorigin="anonymous"></script>

{% block extra_js %}
{% endblock %}
</body>
</html>