cart/urls.py
from django.urls import path
from cart import views, api

app_name = 'cart'

urlpatterns = [
    path('cart-page/', views.CartView.as_view(), name="cart-page"),
    path('cart-detail/<int:id>/', views.DetailView.as_view(), name="cart-detail-page"),

    path('cartAPI/', api.CartViewSet.as_view({
        'get': 'get',
        'post': 'post',
    }), name="cart_api"),

    path('cart-detail-api/<int:id>/', api.CartViewSet.as_view({
        'post': 'delete',
        'get': 'get_detail',
        'put': 'put'
    }), name="cart-delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('market.urls')),
    path('cart/', include('cart.urls')),
    path('transaction/', include('transaction.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('auth/', include('rest_authtoken.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views, api

app_name = 'users'

urlpatterns = [
    path("profile-page/<int:id>/", views.ProfileView.as_view(), name="profile-page"),
    path("register-page/", views.RegisterView.as_view(), name="register-page"),
    path("login-page/", views.LoginView.as_view(), name="login-page"),
    path("update-profile-page/", views.UpdateView.as_view(), name="update-profile-page"),
    path("logout/", views.LogoutView, name="logout"),

    path("register/", api.RegisterViewSet.as_view({
        'post': 'post',
    }), name='register'),

    path("login/", api.LoginViewSet.as_view({
        'post': 'post',
    }), name="login"),

    path("profile/<int:id>/", api.UserViewSet.as_view({
        'get':'get',
        'put': 'put',
    }), name="profile"),
]

users/models.py
from django.db import models
from users.manager import UserManager
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.validators import RegexValidator

letters = RegexValidator(r'^[a-zA-Z. ]*$', 'Only letters are allowed.')


# Create your models here.
class User(AbstractBaseUser, PermissionsMixin):
    """ Overrides Django Base User. """

    #username = None
    email = models.EmailField(max_length=500, unique=True)
    first_name = models.CharField(max_length=80, null=True, blank=True, validators=[letters])
    last_name = models.CharField(max_length=80, null=True, blank=True, validators=[letters])
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    avatar = models.ImageField(blank=True, null=True, upload_to='profile_images', default='defaultAvatar.png')
    date_joined = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = "email"
    objects = UserManager()

    def __str__(self):
        return "{}".format(self.email)

users/views.py
from django.shortcuts import render, get_list_or_404, redirect
from django.views.generic.base import TemplateView
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
# Create your views here.


class RegisterView(TemplateView):
    template_name = "users/register.html"

    def get(self, *args, **kwargs):
        return render(self.request, "users/register.html")


class LoginView(TemplateView):
    template_name = "users/login.html"

    def get(self, *args, **kwargs):
        return render(self.request, "users/login.html")


class UpdateView(TemplateView):
    template_name = "users/update-profile.html"

    def get(self, *args, **kwargs):
        return render(self.request, "users/update-profile.html")


class ProfileView(TemplateView):
    template_name = "users/profile.html"

    def get(self, *args, **kwargs):
        return render(self.request, "users/profile.html")


def LogoutView(request):

    logout(request)
    messages.success(request, 'Account Logged Out!')
    return redirect('market:dashboard')

templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <br>
    <div class="container w-25">
      <small id="valError" class="errMsg"></small>
        <div class="card border-primary mb-3">
            <div class="card-header"><h3>Login</h3></div>
            <div class="card-body">

              <form id="loginUser" action="" class="was-validated" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1" class="form-label mt-4">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp" placeholder="Enter email" required>
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1" class="form-label mt-4">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password" required>
                  </div>
                  <br>
                  <button type="submit" class="btn btn-primary">Login</button>
              </form>

            </div>
        </div>
    </div>
{% endblock %}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/user.js' %}"></script>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <br>
    <section class="h-100 gradient-custom-2">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-lg-9 col-xl-7">

                <div class="card" id="profileCard">

                    <div class="rounded-top text-white d-flex flex-row" style="background-color: #000000; height:250px;">
                        <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
                            <br>
                            <img src="" class="avatarDisp" id="avatarDisp">
                        </div>

                        <div class="ms-3" style="margin-top: 110px;">
                          <h5 id="nameView"></h5>
                          <small id="emailView"></small>
                        </div>
                    </div>
                </div>

                <div class="container">
                    <br>
                    <h3>Products</h3>
                    <br>
                    <div class="row justify-content-center" id="prodContainer">

                    </div>
                </div>

            </div>
        </div>
    </section>

{% endblock %}
{% block extra_js %}

    <script>
        var pathname = window.location.pathname;
        var profileID = pathname.split('/')[3]

        $(document).ready(function(){

            //get profile info
            $.ajax({
                type: "GET",
                url: "users/profile/" + profileID +"/",
                success: function(data){
                    $("#nameView").append(data.first_name + " " + data.last_name);
                    $("#emailView").append(data.email);
                    if(data.email === "{{user.email}}"){
                        $("#profileCard").append("<a href='{% url 'users:update-profile-page' %}' class='btn btn-outline-dark' data-mdb-ripple-color='dark' style='z-index: 1;'>Edit profile</a>");
                    }

                    if(data.avatar !== null){
                        $("#avatarDisp").attr('src', data.avatar);
                    }
                    else{
                       $("#avatarDisp").attr('src', '{% get_media_prefix %}defaultAvatar.png');
                    }
                },
            })

            //get owned products
            let temp = ""
            $.ajax({
                type:"GET",
                url:"/list/",
                success: function(data){
                    $.each(data, function(i,product){
                        var prodOwner = product.owner.split('/')[0]
                        var ownerID = product.owner.split('/')[1]
                        
                        if(ownerID === profileID){
                            temp += "<div class='col-4'>"
                            temp += "<div class='card border-primary mb-3' style='max-width: 20rem;'>"
                            temp += "<div class='card-header'>" + prodOwner + "</div>"
                            temp += "<div class='card-body'>"
                            temp += "<h4 class='card-title'>" + product.product_name +"</h4>"
                            if(product.prod_pic){
                                temp += "<img src='" + product.prod_pic + "' class='img-fluid' id='prodPic'></img>"
                            }
                            else{
                                temp += "<img src='{% get_media_prefix %}defaultProdPic.png' id='prodPic'></img>"
                            }
                            
                            temp += "<a href='users/profile-page/" + ownerID + "/' class='card-link'>Product seller details</a>"

                            if(product.status === 1){
                                temp += "<p style='color:green;'><strong style='color:grey;'>Status: </strong>" + product.status_name + "</p>"
                            }
                            else if(product.status === 2){
                                temp += "<p style='color:red;'><strong style='color:grey;'>Status: </strong>" + product.status_name + "</p>"
                            }
                            temp += "<p><strong>Category: </strong>" + product.category_name + "</p>"

                            temp += "</div><div class='card-footer'>"
                            temp += "<a href='/product-view/" + product.id + "/' class='btn btn-outline-dark' data-mdb-ripple-color='dark' style='z-index: 1;'>Details</a></div></div></div>"
                        }
                        
                    })
                    $("#prodContainer").append(temp);
                }
            })
            
        })


    </script>

{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <br>
    <div class="container w-25">
        <small id="valError" class="errMsg"></small>
        <div class="card border-primary mb-3">
            <div class="card-header"><h3>Register</h3></div>
            <div class="card-body">

            <form id="regUser" action="" novalidate class="was-validated">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1" class="form-label mt-4">Email address</label>
                    <input type="email" class="form-control" name="email" aria-describedby="emailHelp" placeholder="Enter email" required>
                    <small id="emailError" class="errMsg"></small>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="form-label mt-4">Firstname</label>
                    <input type="text" class="form-control" name="fname" placeholder="Firstname" required>
                    <small id="fnameError" class="errMsg"></small>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="form-label mt-4">Lastname</label>
                    <input type="text" class="form-control" name="lname" placeholder="Lastname" required>
                    <small id="lnameError" class="errMsg"></small>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="form-label mt-4">Password</label>
                    <input type="password" class="form-control" name="password" placeholder="Password" required>
                    <small id="passError" class="errMsg"></small>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="form-label mt-4">Confirm Password</label>
                    <input type="password" class="form-control" name="password2" placeholder="Password" required>
                    <small id="passError2" class="errMsg"></small>
                </div>
                <br>
                <button type="submit" class="btn btn-primary" id="frmBtn">Register</button>
            </form>
            
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/user.js' %}"></script>
{% endblock %}

templates/users/update-profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<br>
<div class="container w-25">
    <small id="valError" class="errMsg"></small>
    
            
    {% if user.is_authenticated %}
    <div class="card border-primary mb-3">
        <div class="card-header"><h3>Edit</h3></div>
        <div class="card-body">
          <form id="editUser" action="" class="was-validated" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1" class="form-label mt-4">Firstname</label>
                <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Firstname" required>
                <small id="fnameError" class="errMsg"></small>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1" class="form-label mt-4">Lastname</label>
                <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Lastname" required>
                <small id="lnameError" class="errMsg"></small>
              </div>
              <div class="form-group">
                <label for="formFile" class="form-label mt-4">Avatar</label>
                <input class="form-control" type="file" id="avatar" name="avatar" accept="image/*">
                <small id="imgError" class="errMsg"></small>
              </div>
              <br>
              <button type="submit" class="btn btn-primary">Edit</button>
          </form>

          {% else %}
          <div class="card border-primary mb-3">
            <div class="card-header"><h3>You are not logged in</h3></div>
            <div class="card-body">

          <a href='{% url 'users:login-page' %}' class='btn btn-outline-dark' data-mdb-ripple-color='dark' style='z-index: 1;'>Login</a>
          
          {% endif %}
          
        </div>
    </div>
</div>
{% endblock %}
{% block extra_js %}

    {% if user.is_authenticated %}
    <script>

        // JavaScript function to get cookie by name
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');

        //get user
         $(document).ready(function(){

            $.ajax({
                type: "GET",
                url: "{% url 'users:profile' user.id %}",
                success: function(data){
                    $('#first_name').val(data.first_name)
                    $('#last_name').val(data.last_name)
                    $("#nameView").append(data.first_name + " " + data.last_name);
                    $("#emailView").append(data.email);
                    if(data.avatar !== null){
                        $("#avatarDisp").attr('src', data.avatar);
                    }
                    else{
                       $("#avatarDisp").attr('src', '{% get_media_prefix %}defaultAvatar.png');
                    }
                },
            })
        })

        //edit user
        let namelvalCheck = false

        $("form#editUser").submit(function(event){
            event.preventDefault()
            var formData = new FormData()

            var fname = $("#first_name").val()
            var lname = $("#last_name").val()

            if(fname && lname){
                if($('#avatar').prop('files')[0] != undefined){
                    formData.append('avatar', $('#avatar')[0].files[0])
                }
                valNames(fname, lname)
                formData.append('first_name', fname)
                formData.append('last_name', lname)

                if(namelvalCheck === true){
                    $.ajax({
                        type:"PUT",
                        url:"{% url 'users:profile' user.id %}",
                        data:formData,
                        processData: false,
                        contentType: false,
                        beforeSend: function(xhr){
                            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                        },
                        success:function(){
                            window.location.href = "{% url 'users:profile-page' user.id %}"
                        },
                        error:function(error){
                            console.log(error)
                            $('#imgError').show()
                            $("#imgError").html("Don't be stupid this ain't an image file")
                        }
                    })
                }

            }
            else{
                $('#valError').show()
                $("#valError").html("All fields must have valid input")
            }
        })

        //Validates names
        function valNames(fn,ln){
            let regex = /^[a-z ,.'-]+$/i
            if(fn.length>80){
                $('#fnameError').show()
                $("#fnameError").html("First Name exceeds max length please try again")
                namelvalCheck = false
                return false
            }
            if(ln.length>80){
                $('#lnameError').show()
                $("#lnameError").html("Last Name exceeds max length please try again")
                namelvalCheck = false
                return false
            }
            if(!regex.test(fn)){
                $('#fnameError').show()
                $("#fnameError").html("Invalid First Name please try again ")
                namelvalCheck = false
                return false
            }
            if(!regex.test(ln)){
                $('#lnameError').show()
                $("#lnameError").html("Invalid Last Name please try again ")
                namelvalCheck = false
                return false
            }
            $('#fnameError').hide()
            $('#lnameError').hide()
            namelvalCheck = true
            return true
        

        }

    </script>

    {% endif %}

{% endblock %}